version: "3.9"

services:
  captcha-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DEBUG=false
      - SIGNING_SECRET=bir_sirr_var
    volumes:
      - ./logs:/app/logs
